/* oxlint-disable next/no-html-link-for-pages */
import { BreadcrumbLd, JsonLd, PageShell, SourceNote } from '@/components/organic-ui';
import { bulletinIndicators, bulletinMetric } from '@/lib/bulletin-data';
import { ORIGIN, fmt, indicatorById, monthLabel, sourceUpdated, windowLabel } from '@/lib/organic-data';

export function BulletinPage({ end }: { end: string }) {
  const lines = bulletinIndicators.map((key) => ({ item: indicatorById(key)!, result: bulletinMetric(key, end) }));
  const path = `/boletins/${end}`, shareUrl = `${ORIGIN}${path}`, previousEnd = `${Number(end.slice(0, 4)) - 1}${end.slice(4)}`;
  return <PageShell crumbs={[{ label: 'Boletins', path: '/boletins' }, { label: monthLabel(end) }]}>
    <BreadcrumbLd items={[{ name: 'Boletins', path: '/boletins' }, { name: `Boletim de ${monthLabel(end)}`, path }]} />
    <JsonLd value={{ '@context': 'https://schema.org', '@type': 'Report', '@id': `${shareUrl}#report`, url: shareUrl, name: `Boletim de registros policiais até ${monthLabel(end)}`, dateModified: sourceUpdated, temporalCoverage: windowLabel(end, 12), isPartOf: { '@id': `${ORIGIN}/boletins#page` }, citation: 'ISP-RJ, série mensal por CISP' }} />
    <p className="text-sm font-semibold uppercase tracking-wide text-[#2455dc]">Levantamento reproduzível · ISP-RJ</p><h1 className="mt-2 max-w-4xl text-3xl font-semibold tracking-tight sm:text-4xl">Registros policiais no Rio até {monthLabel(end)}</h1><p className="mt-3 max-w-3xl text-base leading-7 text-[#526078]">Comparamos {windowLabel(previousEnd, 12)} com {windowLabel(end, 12)}, somando as 41 CISPs do município. As duas janelas têm 12 meses e terminam no mesmo mês do ano.</p>
    <div className="mt-7 overflow-x-auto rounded-2xl border border-[#dce2ed] bg-white"><table className="w-full min-w-[620px] text-left text-sm"><caption className="p-4 text-left font-semibold">Janelas equivalentes de 12 meses · município do Rio de Janeiro</caption><thead className="bg-[#eaf0fc]"><tr><th className="px-4 py-3">Indicador</th><th className="px-4 py-3 text-right">{windowLabel(previousEnd, 12)}</th><th className="px-4 py-3 text-right">{windowLabel(end, 12)}</th><th className="px-4 py-3 text-right">Variação</th></tr></thead><tbody>{lines.map(({ item, result }) => <tr key={item.id} className="border-t border-[#e7ebf2]"><th className="px-4 py-3"><a className="font-semibold text-[#2455dc] underline" href={`/indicadores/${item.id}`}>{item.label}</a><span className="block text-[#526078]">{item.unit}</span></th><td className="px-4 py-3 text-right tabular-nums">{fmt(result?.previous)}</td><td className="px-4 py-3 text-right tabular-nums">{fmt(result?.count)}</td><td className="px-4 py-3 text-right tabular-nums">{result?.change == null ? 'Indisponível' : `${fmt(result.change, 1)}%`}</td></tr>)}</tbody></table></div>
    <p className="mt-5 max-w-4xl leading-7">Estas mudanças descrevem registros recebidos e classificados pelo ISP-RJ. Não medem todos os fatos ocorridos nem a probabilidade de uma pessoa ser vítima. Categorias podem se sobrepor; a tabela não tem um total geral.</p><p className="mt-3 text-sm text-[#526078]">Fonte observada como modificada em {sourceUpdated}. Valores calculados do <a className="underline" href="/data/crime-rio-snapshot.json">snapshot JSON</a>, com <a className="underline" href="/dados">dicionário e downloads</a>. Se algum mês de uma janela estiver ausente, a métrica fica indisponível em vez de usar cobertura parcial.</p>
    <section className="mt-7 rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Compartilhar este período</h2><p className="mt-2 text-sm leading-6 text-[#526078]">Este endereço permanece ligado à competência {end}; ele não muda automaticamente quando um novo mês é publicado.</p><div className="mt-3 flex flex-wrap gap-4 text-sm font-semibold text-[#2455dc]"><a className="underline" href={shareUrl}>Link estável</a><a className="underline" href={`https://wa.me/?text=${encodeURIComponent(shareUrl)}`} rel="noreferrer">Compartilhar link no WhatsApp</a></div></section>
    <div className="mt-7"><SourceNote /></div>
  </PageShell>;
}
