'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import * as maplibregl from 'maplibre-gl';
import maplibreWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import type { ExpressionSpecification, Map as MapLibreMap, MapGeoJSONFeature } from 'maplibre-gl';
import type { FeatureCollection, Geometry, Position } from 'geojson';
import Link from 'next/link';
import { motion, useReducedMotion } from 'motion/react';
import 'maplibre-gl/dist/maplibre-gl.css';
import { ArrowDownRight, ArrowUpRight, Database, FileText, Info, MapPinned, Share2 } from 'lucide-react';
import { Button, buttonVariants } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Indicator = { id: string; label: string; unit: string; note?: string };
type DataRow = { cisp: number; aisp: number; risp: number; period: string; phase: number; values: Record<string, number> };
type Snapshot = { generatedAt: string; live?: boolean; latestPeriod: string; latestPhase: number[]; indicators: Indicator[]; coverage: { municipality: string; cispCount: number; months: number }; rows: DataRow[]; source: { title: string; publisher: string; landingPage: string; lastModified?: string; sha256?: string } };
type AreaStat = { cisp: number; current: number; previous: number; change: number | null; latest: number };
type CispProperties = { cisp: number; aisp?: number; current?: number; previous?: number; change?: number | null; latest?: number };
type HoverState = { x: number; y: number; cisp: number; current: number; change: number | null };

const overviewIds = ['total_roubos', 'total_furtos', 'letalidade_violenta', 'estelionato'] as const;
maplibregl.setWorkerUrl(maplibreWorkerUrl);
const mapStyle = {
  version: 8 as const,
  sources: { osm: { type: 'raster' as const, tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256, attribution: '© OpenStreetMap contributors' } },
  layers: [{ id: 'osm', type: 'raster' as const, source: 'osm', paint: { 'raster-opacity': 0.62, 'raster-saturation': -0.75, 'raster-contrast': -0.12, 'raster-brightness-max': 0.94 } }],
};
const colorExpression: ExpressionSpecification = ['interpolate', ['linear'], ['coalesce', ['get', 'change'], 0], -50, '#2d7180', -10, '#83adb1', 0, '#ded8cb', 10, '#d39a78', 50, '#be714f'];

function sum(rows: DataRow[], indicator: string) { return rows.reduce((total, row) => total + (row.values[indicator] ?? 0), 0); }
function formatPeriod(period: string) { const [year, month] = period.split('-').map(Number); return new Intl.DateTimeFormat('pt-BR', { month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(Date.UTC(year, month - 1, 1))).replace('.', ''); }
function fmtChange(change: number | null) { if (change === null) return 'volume pequeno'; return `${change > 0 ? '+' : ''}${change.toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`; }
function flattenCoordinates(geometry: Geometry): Position[] { if (geometry.type === 'Polygon') return geometry.coordinates.flat(); if (geometry.type === 'MultiPolygon') return geometry.coordinates.flat(2); return []; }

export function CrimeExplorer() {
  const mapNode = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const selectedCispRef = useRef(16); const userSelectedRef = useRef(false); const reducedMotion = useReducedMotion();
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [boundaries, setBoundaries] = useState<FeatureCollection<Geometry, CispProperties> | null>(null); const [hover, setHover] = useState<HoverState | null>(null); const [loadError, setLoadError] = useState(false);
  const [indicator, setIndicator] = useState(() => typeof window === 'undefined' ? 'total_roubos' : new URLSearchParams(window.location.search).get('indicador') || 'total_roubos');
  const [selectedCisp, setSelectedCisp] = useState(() => { if (typeof window === 'undefined') return 16; const value = Number(new URLSearchParams(window.location.search).get('cisp')); return Number.isFinite(value) && value > 0 ? value : 16; });

  useEffect(() => {
    const loadSnapshot = async (): Promise<Snapshot> => { const live = await fetch('/api/crime?v=2'); if (live.ok) { const data = await live.json() as Snapshot; if (data.indicators.some((item) => item.id === 'total_roubos')) return data; } const fallback = await fetch('/data/crime-rio-snapshot.json'); if (!fallback.ok) throw new Error('No data source'); return fallback.json() as Promise<Snapshot>; };
    Promise.all([loadSnapshot(), fetch('/data/cisp-rio.geojson').then((response) => response.json() as Promise<FeatureCollection<Geometry, CispProperties>>)]).then(([data, geo]) => { setSnapshot(data); setBoundaries(geo); }).catch(() => setLoadError(true));
  }, []);
  useEffect(() => { selectedCispRef.current = selectedCisp; const url = new URL(window.location.href); url.searchParams.set('cisp', String(selectedCisp)); url.searchParams.set('indicador', indicator); window.history.replaceState(null, '', url); }, [selectedCisp, indicator]);

  const periods = useMemo(() => snapshot ? [...new Set(snapshot.rows.map((row) => row.period))].sort() : [], [snapshot]); const currentPeriods = useMemo(() => periods.slice(-12), [periods]); const previousPeriods = useMemo(() => periods.slice(-24, -12), [periods]);
  const stats = useMemo(() => {
    if (!snapshot || periods.length < 24) return [] as AreaStat[]; const currentWindow = new Set(currentPeriods); const previousWindow = new Set(previousPeriods); const latest = periods.at(-1);
    return [...new Set(snapshot.rows.map((row) => row.cisp))].sort((a, b) => a - b).map((cisp) => { const rows = snapshot.rows.filter((row) => row.cisp === cisp); const current = sum(rows.filter((row) => currentWindow.has(row.period)), indicator); const previous = sum(rows.filter((row) => previousWindow.has(row.period)), indicator); return { cisp, current, previous, change: current + previous >= 20 && previous > 0 ? ((current - previous) / previous) * 100 : null, latest: sum(rows.filter((row) => row.period === latest), indicator) }; });
  }, [snapshot, periods, currentPeriods, previousPeriods, indicator]);
  const enrichedGeo = useMemo(() => { if (!boundaries || !stats.length) return null; const byCisp = new Map(stats.map((item) => [item.cisp, item])); return { ...boundaries, features: boundaries.features.map((feature) => ({ ...feature, properties: { ...feature.properties, ...byCisp.get(Number(feature.properties.cisp)) } })) }; }, [boundaries, stats]);
  const enrichedGeoRef = useRef(enrichedGeo);
  const mapReady = Boolean(enrichedGeo);

  useEffect(() => { enrichedGeoRef.current = enrichedGeo; const source = mapRef.current?.getSource('cisp') as maplibregl.GeoJSONSource | undefined; if (source && enrichedGeo) void source.setData(enrichedGeo); }, [enrichedGeo]);

  useEffect(() => {
    const initialGeo = enrichedGeoRef.current; if (!mapNode.current || !mapReady || !initialGeo || mapRef.current) return;
    const map = new maplibregl.Map({ container: mapNode.current, style: mapStyle, center: [-43.34, -22.93], zoom: 9.65, minZoom: 8.5, maxZoom: 15, attributionControl: false });
    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-right'); map.addControl(new maplibregl.AttributionControl({ compact: true }), 'bottom-left');
    map.on('load', () => {
      map.addSource('cisp', { type: 'geojson', data: initialGeo });
      map.addLayer({ id: 'cisp-fill', type: 'fill', source: 'cisp', paint: { 'fill-color': colorExpression, 'fill-opacity': 0.66, 'fill-color-transition': { duration: reducedMotion ? 0 : 320 } } });
      map.addLayer({ id: 'cisp-line', type: 'line', source: 'cisp', paint: { 'line-color': '#15313d', 'line-width': 1, 'line-opacity': 0.68 } });
      map.addLayer({ id: 'cisp-selected', type: 'line', source: 'cisp', filter: ['==', ['get', 'cisp'], selectedCispRef.current], paint: { 'line-color': '#e2af4a', 'line-width': 4, 'line-blur': 0.4 } });
      map.on('click', 'cisp-fill', (event) => { const feature = event.features?.[0] as MapGeoJSONFeature | undefined; if (feature?.properties?.cisp) { userSelectedRef.current = true; setSelectedCisp(Number(feature.properties.cisp)); } });
      map.on('mousemove', 'cisp-fill', (event) => { const feature = event.features?.[0] as MapGeoJSONFeature | undefined; if (!feature) return; map.getCanvas().style.cursor = 'pointer'; setHover({ x: event.point.x, y: event.point.y, cisp: Number(feature.properties.cisp), current: Number(feature.properties.current), change: feature.properties.change == null ? null : Number(feature.properties.change) }); });
      map.on('mouseleave', 'cisp-fill', () => { map.getCanvas().style.cursor = ''; setHover(null); }); map.resize();
    });
    const observer = new ResizeObserver(() => map.resize()); observer.observe(mapNode.current); mapRef.current = map;
    return () => { observer.disconnect(); map.remove(); mapRef.current = null; };
  }, [mapReady, reducedMotion]);
  useEffect(() => {
    const map = mapRef.current; if (!map?.getLayer('cisp-selected')) return; map.setFilter('cisp-selected', ['==', ['get', 'cisp'], selectedCisp]);
    if (!userSelectedRef.current || !boundaries) return; const feature = boundaries.features.find((item) => Number(item.properties.cisp) === selectedCisp); const coordinates = feature ? flattenCoordinates(feature.geometry) : [];
    if (coordinates.length) { const bounds = coordinates.reduce((box, coordinate) => box.extend(coordinate as [number, number]), new maplibregl.LngLatBounds(coordinates[0] as [number, number], coordinates[0] as [number, number])); map.fitBounds(bounds, { padding: 72, duration: reducedMotion ? 0 : 520, maxZoom: 12 }); } userSelectedRef.current = false;
  }, [selectedCisp, boundaries, reducedMotion]);

  const selected = stats.find((item) => item.cisp === selectedCisp); const selectedIndicator = snapshot?.indicators.find((item) => item.id === indicator); const cityTotal = sum(snapshot?.rows.filter((row) => currentPeriods.includes(row.period)) ?? [], indicator);
  const selectedSeries = (snapshot?.rows.filter((row) => row.cisp === selectedCisp).slice(-12) ?? []).map((row) => ({ period: row.period, value: row.values[indicator] ?? 0 })); const seriesMax = Math.max(1, ...selectedSeries.map((item) => item.value));
  const overview = overviewIds.map((id) => { const meta = snapshot?.indicators.find((item) => item.id === id); const current = sum(snapshot?.rows.filter((row) => currentPeriods.includes(row.period)) ?? [], id); const previous = sum(snapshot?.rows.filter((row) => previousPeriods.includes(row.period)) ?? [], id); return { id, label: meta?.label ?? id, unit: meta?.unit ?? 'registros', current, change: current + previous >= 20 && previous > 0 ? ((current - previous) / previous) * 100 : null }; });
  async function share() { const text = `${selectedIndicator?.label ?? 'Registros'} na CISP ${selectedCisp}: ${selected ? fmtChange(selected.change) : ''} na comparação de 12 meses. Dados oficiais ISP-RJ; registros não representam risco individual.`; if (navigator.share) await navigator.share({ title: 'Mapa Aberto RJ', text, url: window.location.href }); else await navigator.clipboard.writeText(`${text} ${window.location.href}`); }
  if (loadError) return <main className="grid min-h-screen place-items-center bg-background p-6"><div className="max-w-md border-l-4 border-[#be714f] bg-card p-6"><h1 className="font-heading text-xl font-semibold">Os dados não carregaram.</h1><p className="mt-2 text-sm text-muted-foreground">Tente novamente. A fonte e a data sempre aparecem quando a leitura está disponível.</p></div></main>;

  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-[#15313d]/15 bg-background/95 px-4 py-3 backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1540px] items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center bg-[#15313d] text-[#f5f1e8]"><MapPinned className="size-5" /></div><div><p className="font-heading text-base font-semibold tracking-tight">Mapa Aberto RJ</p><p className="text-[11px] text-muted-foreground">Atlas cívico dos registros policiais</p></div></div><div className="flex items-center gap-3 text-[11px] text-muted-foreground"><span className="hidden sm:inline">Rio de Janeiro · dados até {snapshot ? formatPeriod(snapshot.latestPeriod) : '—'}</span><span className="inline-flex items-center gap-1.5 font-medium text-[#315e59]"><Database className="size-3.5" /> ISP-RJ</span></div></div></header>
    <section className="mx-auto max-w-[1540px] px-4 pb-8 pt-5 md:px-8 md:pt-7">
      <div className="grid gap-4 border-b border-[#15313d]/15 pb-5 lg:grid-cols-[minmax(260px,0.7fr)_minmax(0,1.3fr)] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#52717a]">Visão geral da cidade</p><h1 className="mt-1 max-w-xl font-heading text-3xl font-semibold leading-tight tracking-[-0.035em] md:text-4xl">O que mudou no Rio?</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Primeiro o panorama. Depois, a distribuição por área e tipo de registro.</p></div><div className="flex gap-x-6 gap-y-3 overflow-x-auto pb-1 lg:grid lg:grid-cols-4 lg:overflow-visible">{overview.map((item) => <button key={item.id} type="button" onClick={() => setIndicator(item.id)} aria-pressed={indicator === item.id} className={`min-w-[150px] border-l-2 py-1 pl-3 text-left transition-colors ${indicator === item.id ? 'border-[#e2af4a]' : 'border-[#15313d]/18 hover:border-[#52717a]'}`}><span className="block text-[11px] font-medium text-muted-foreground">{item.label}</span><motion.strong key={`${item.id}-${item.current}`} initial={reducedMotion ? false : { opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }} className="mt-0.5 block font-heading text-xl font-semibold tabular-nums">{snapshot ? item.current.toLocaleString('pt-BR') : '—'}</motion.strong><span className="flex items-center gap-1 text-[11px] text-muted-foreground">{item.change != null && item.change > 0 ? <ArrowUpRight className="size-3 text-[#a4543d]" /> : <ArrowDownRight className="size-3 text-[#326675]" />} {snapshot ? fmtChange(item.change) : '—'} · 12 meses</span></button>)}</div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_350px]">
        <section className="relative order-1 h-[58vh] min-h-[430px] overflow-hidden border border-[#15313d]/18 bg-[#d9e3e2] lg:h-[calc(100vh-245px)] lg:min-h-[620px]"><div ref={mapNode} className="h-full w-full" /><div className="absolute left-3 right-14 top-3 flex max-w-xl flex-col gap-2 bg-[#f5f1e8]/94 p-3 shadow-sm backdrop-blur md:right-auto md:flex-row md:items-end"><div className="min-w-0 flex-1 md:min-w-[260px]"><label htmlFor="indicator-select" className="mb-1 block text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Quebrar por tipo</label><Select value={indicator} onValueChange={(value) => setIndicator(String(value))}><SelectTrigger id="indicator-select" className="h-9 w-full border-[#15313d]/20 bg-white/70"><SelectValue /></SelectTrigger><SelectContent>{snapshot?.indicators.map((item) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="shrink-0 text-[10px] leading-4 text-muted-foreground md:max-w-[180px]"><strong className="text-foreground">Cor:</strong> variação contra os 12 meses anteriores</div></div>
          {hover && <div className="pointer-events-none absolute z-10 min-w-[150px] border border-[#15313d]/15 bg-[#15313d] px-3 py-2 text-[#f5f1e8] shadow-xl" style={{ left: `min(calc(100% - 170px), ${hover.x + 14}px)`, top: Math.max(76, hover.y - 28) }}><p className="text-[10px] uppercase tracking-[0.1em] text-[#b9d9de]">CISP {hover.cisp}</p><p className="mt-0.5 text-sm font-semibold">{hover.current.toLocaleString('pt-BR')} {selectedIndicator?.unit}</p><p className="text-[11px]">{fmtChange(hover.change)} em 12 meses</p></div>}
          <div className="pointer-events-none absolute bottom-3 left-3 bg-[#f5f1e8]/94 px-3 py-2 text-[10px] shadow-sm backdrop-blur"><p className="mb-1.5 font-semibold">Variação em 12 meses</p><div className="flex items-center gap-1.5"><span className="size-2.5 bg-[#2d7180]" /><span>caiu</span><span className="ml-2 size-2.5 bg-[#ded8cb]" /><span>estável</span><span className="ml-2 size-2.5 bg-[#be714f]" /><span>subiu</span></div></div></section>
        <motion.aside key={`${selectedCisp}-${indicator}`} initial={reducedMotion ? false : { opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.25 }} className="order-2 border-t-4 border-[#e2af4a] bg-card p-5 shadow-sm lg:min-h-[620px]"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Área selecionada · fase {snapshot?.latestPhase?.join('/') ?? '—'}</p><h2 className="mt-1 font-heading text-3xl font-semibold tracking-tight">CISP {selectedCisp}</h2><p className="text-sm text-muted-foreground">Circunscrição da {selectedCisp}ª DP</p></div><div className={`mt-1 flex items-center gap-1 text-sm font-semibold ${selected?.change != null && selected.change > 0 ? 'text-[#a4543d]' : 'text-[#326675]'}`}>{selected?.change != null && selected.change > 0 ? <ArrowUpRight className="size-5" /> : <ArrowDownRight className="size-5" />}{selected ? fmtChange(selected.change) : '—'}</div></div><div className="mt-7"><p className="text-xs text-muted-foreground">{selectedIndicator?.label}</p><p className="mt-1 font-heading text-4xl font-semibold tabular-nums">{selected?.current.toLocaleString('pt-BR') ?? '—'} <span className="text-sm font-normal text-muted-foreground">{selectedIndicator?.unit}</span></p><p className="mt-1 text-xs text-muted-foreground">contra {selected?.previous.toLocaleString('pt-BR') ?? '—'} nos 12 meses anteriores</p></div>
          <div className="mt-7 border-y border-[#15313d]/12 py-5"><div className="mb-3 flex items-center justify-between text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><span>Últimos 12 meses</span><span>{selectedIndicator?.unit}</span></div><div className="flex h-28 items-end gap-1.5" aria-label="Série dos doze meses recentes">{selectedSeries.map((item) => <div key={item.period} className="group relative flex h-full flex-1 items-end"><motion.div initial={reducedMotion ? false : { height: 0 }} animate={{ height: `${Math.max(5, (item.value / seriesMax) * 100)}%` }} transition={{ duration: 0.32 }} className="w-full bg-[#527f8d] transition-colors group-hover:bg-[#15313d]" title={`${formatPeriod(item.period)}: ${item.value}`} /><span className="absolute -bottom-4 left-1/2 hidden -translate-x-1/2 text-[8px] text-muted-foreground first:block last:block">{item.period.slice(5)}</span></div>)}</div></div>
          {selectedIndicator?.note && <div className="mt-6 flex gap-2 text-xs leading-5 text-muted-foreground"><Info className="mt-0.5 size-4 shrink-0" /><p>{selectedIndicator.note}</p></div>}<div className="mt-6 bg-[#edf1ee] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Contexto da cidade</p><p className="mt-1 font-heading text-2xl font-semibold tabular-nums">{cityTotal.toLocaleString('pt-BR')}</p><p className="text-xs text-muted-foreground">{selectedIndicator?.unit ?? 'registros'} nas 41 CISPs.</p></div><div className="mt-6 flex flex-wrap gap-2"><Button onClick={() => void share()} className="h-9 bg-[#15313d] text-[#f5f1e8] hover:bg-[#284956]"><Share2 /> Compartilhar</Button><Link href="/metodologia" className={buttonVariants({ variant: 'outline', className: 'h-9' })}><FileText /> Entenda o número</Link></div></motion.aside>
      </div>
      <footer className="mt-4 flex flex-col justify-between gap-2 border-t border-[#15313d]/15 pt-4 text-[11px] leading-5 text-muted-foreground md:flex-row"><p>CISP é área de delegacia, não bairro. Registros comunicados à polícia não equivalem ao risco individual de uma rua.</p><p>{snapshot?.live ? 'Fonte consultada automaticamente nesta sessão.' : 'Snapshot validado usado como contingência.'} <a href="https://www.ispdados.rj.gov.br/EstSeguranca.html" target="_blank" rel="noreferrer" className="font-medium text-[#315e59] underline underline-offset-4">Fonte ISP-RJ</a></p></footer>
    </section>
  </main>;
}
