/* oxlint-disable next/no-html-link-for-pages */
import type { Metadata } from 'next';
import { BreadcrumbLd, JsonLd, PageShell } from '@/components/organic-ui';
import { ORIGIN, canonical, census, collected, data, fmt, indicatorList, monthLabel, period, sourceUpdated } from '@/lib/organic-data';

export const metadata: Metadata = { title: 'Dados e downloads | Mapa da Criminalidade RJ', description: `Baixe a série mensal por CISP até ${monthLabel(period)} em JSON e CSV, com dicionário, cobertura, proveniência e limites de uso.`, alternates: { canonical: canonical('/dados') } };
export default function DataPage() {
  const csv = `${ORIGIN}/data/crime-rio-history-cisp.csv`;
  const json = `${ORIGIN}/data/crime-rio-snapshot.json`;
  return <PageShell crumbs={[{ label: 'Dados' }]}>
    <BreadcrumbLd items={[{ name: 'Dados', path: '/dados' }]} />
    <JsonLd value={{ '@context': 'https://schema.org', '@type': 'Dataset', '@id': `${ORIGIN}/dados#dataset`, name: 'Registros policiais mensais por CISP no município do Rio de Janeiro', description: `Recorte das 41 CISPs do município do Rio de Janeiro da série mensal do ISP-RJ, com ${indicatorList.length} indicadores e cobertura de ${data.coverage.months} meses até ${monthLabel(period)}.`, creator: { '@type': 'Organization', name: 'Instituto de Segurança Pública do Estado do Rio de Janeiro', url: 'https://www.ispdados.rj.gov.br/' }, isBasedOn: data.source.url, url: `${ORIGIN}/dados`, temporalCoverage: `${data.rows[0].period}/${period}`, spatialCoverage: { '@type': 'Place', name: 'Município do Rio de Janeiro, RJ, Brasil' }, dateModified: sourceUpdated, distribution: [{ '@type': 'DataDownload', contentUrl: json, encodingFormat: 'application/json', name: 'Snapshot mensal por CISP, JSON' }, { '@type': 'DataDownload', contentUrl: csv, encodingFormat: 'text/csv', name: 'Série histórica por CISP, CSV' }] }} />
    <p className="text-sm font-semibold uppercase tracking-wide text-[#2455dc]">Dados reutilizáveis</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Baixe e confira os registros</h1><p className="mt-3 max-w-3xl text-base leading-7 text-[#526078]">Os arquivos mantêm o identificador de CISP, o mês e a unidade de cada indicador. O snapshot recente vai de {monthLabel(data.rows[0].period)} a {monthLabel(period)}. A série histórica CSV segue até {monthLabel(period)}; consulte a metodologia para mudanças territoriais antigas.</p>
    <div className="mt-7 grid gap-4 sm:grid-cols-2"><a className="rounded-2xl bg-[#172235] p-6 text-white transition hover:bg-[#253854]" href="/data/crime-rio-snapshot.json" download><h2 className="text-xl font-semibold">Snapshot recente · JSON</h2><p className="mt-2 text-sm text-white/80">{fmt(data.rows.length)} linhas CISP/mês · {data.coverage.months} meses · {indicatorList.length} indicadores</p><span className="mt-5 inline-block underline">Baixar JSON</span></a><a className="rounded-2xl border border-[#dce2ed] bg-white p-6 transition hover:border-[#2455dc]" href="/data/crime-rio-history-cisp.csv" download><h2 className="text-xl font-semibold">Série histórica · CSV</h2><p className="mt-2 text-sm text-[#526078]">Desde 2003; leia as mudanças de cobertura e a semântica de valores ausentes.</p><span className="mt-5 inline-block font-semibold text-[#2455dc] underline">Baixar CSV</span></a></div>
    <section className="mt-8 rounded-2xl border border-[#dce2ed] bg-white p-6"><h2 className="text-xl font-semibold">Fonte e datas</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Período mais recente</dt><dd>{monthLabel(period)}</dd></div><div><dt className="font-semibold">Publicação da fonte observada</dt><dd>{sourceUpdated} (cabeçalho Last-Modified do arquivo do ISP)</dd></div><div><dt className="font-semibold">Coleta deste snapshot</dt><dd>{new Date(collected).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' })}</dd></div><div><dt className="font-semibold">Fonte original</dt><dd><a className="underline" href={data.source.url}>ISP-RJ · CSV mensal por CISP</a></dd></div><div><dt className="font-semibold">Integridade do arquivo fonte</dt><dd className="break-all font-mono text-xs">SHA-256 {data.source.sha256}</dd></div><div><dt className="font-semibold">População e limite territorial</dt><dd><a className="underline" href={census.source.methodologyUrl}>IBGE, Censo 2022</a> · <a className="underline" href={census.source.cispBoundaryUrl}>geometria completa ISP-RJ</a></dd></div></dl></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Dicionário de campos</h2><p className="mt-2 text-sm text-[#526078]">No JSON, as contagens ficam dentro de <code>values</code>. No CSV histórico, cada indicador é uma coluna própria.</p><div className="mt-4 overflow-x-auto rounded-2xl border border-[#dce2ed] bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#eaf0fc]"><tr><th className="px-4 py-3">Campo</th><th className="px-4 py-3">Significado e unidade</th></tr></thead><tbody>{[['cisp', 'Número estável da circunscrição policial; não equivale a bairro.'], ['period', 'Competência no formato AAAA-MM.'], ['aisp / risp', 'Áreas integradas de segurança pública relacionadas à CISP.'], ['phase', 'Fase de consolidação indicada pelo ISP.'], ['values', 'Objeto com as contagens dos indicadores abaixo; null significa ausente, jamais zero.']].map(([field, meaning]) => <tr key={field} className="border-t border-[#e7ebf2]"><th className="px-4 py-3 font-mono font-medium" scope="row">{field}</th><td className="px-4 py-3">{meaning}</td></tr>)}{indicatorList.map((item) => <tr key={item.id} className="border-t border-[#e7ebf2]"><th className="px-4 py-3 font-mono font-medium" scope="row"><a className="text-[#2455dc] underline" href={`/indicadores/${item.id}`}>{item.id}</a></th><td className="px-4 py-3">{item.label} · {item.unit}. {item.definition}</td></tr>)}</tbody></table></div></section>
    <p className="mt-7 text-sm leading-6 text-[#526078]">Registros comunicados à polícia não cobrem fatos não notificados. Agregados se sobrepõem a componentes; casos e vítimas não devem ser somados. Uma CISP pode conter bairros ou partes de bairros. A taxa por 100 mil usa população residente do Censo 2022 e não mede probabilidade individual. <a className="underline" href="/metodologia">Leia a metodologia completa</a>. Consulte os termos de reutilização diretamente nas fontes oficiais antes de redistribuir os dados.</p>
  </PageShell>;
}
