/* oxlint-disable next/no-html-link-for-pages */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { BreadcrumbLd, JsonLd, PageShell, RegionMap, SeriesTable, SourceNote } from '@/components/organic-ui';
import { ORIGIN, areaById, canonical, collected, fmt, ids, indicatorById, metrics, monthLabel, monthlySeries, period, populationById, queryFor, sourceUpdated, windowLabel } from '@/lib/organic-data';

type Params = { params: Promise<{ slug: string }> };
function idFor(slug: string) { const match = /^cisp-([1-9]\d*)$/.exec(slug); return match ? Number(match[1]) : null; }
export function generateStaticParams() { return ids.map((id) => ({ slug: `cisp-${id}` })); }
export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const id = idFor((await params).slug) ?? 0, area = areaById(id);
  if (!area) return { title: 'CISP inexistente' };
  return { title: `CISP ${id} · ${area.territorialUnit} | Mapa da Criminalidade RJ`, description: `Registros policiais da CISP ${id}, ${area.territorialUnit}: série mensal, bairros relacionados, população e método. Dados até ${monthLabel(period)}.`, alternates: { canonical: canonical(`/regioes/cisp-${id}`) }, openGraph: { title: `CISP ${id} · ${area.territorialUnit}`, url: canonical(`/regioes/cisp-${id}`) } };
}
export default async function Region({ params }: Params) {
  const id = idFor((await params).slug) ?? 0, area = areaById(id);
  if (!area) notFound();
  const pop = populationById(id);
  const primary = indicatorById('total_roubos')!;
  const current = metrics(primary.id).find((row) => row.cisp === id);
  const others = ['total_furtos', 'roubo_rua', 'letalidade_violenta'].map((key) => ({ meta: indicatorById(key)!, value: metrics(key).find((row) => row.cisp === id) }));
  const path = `/regioes/cisp-${id}`;
  return <PageShell crumbs={[{ label: 'Regiões', path: '/regioes' }, { label: `CISP ${id}` }]}>
    <BreadcrumbLd items={[{ name: 'Regiões', path: '/regioes' }, { name: `CISP ${id}`, path }]} />
    <JsonLd value={{ '@context': 'https://schema.org', '@type': 'WebPage', '@id': `${ORIGIN}${path}#webpage`, url: `${ORIGIN}${path}`, name: `CISP ${id} · ${area.territorialUnit}`, description: `Série mensal de registros policiais da CISP ${id} até ${monthLabel(period)}.`, dateModified: sourceUpdated, isPartOf: { '@id': `${ORIGIN}/#website` }, spatialCoverage: { '@type': 'Place', name: `CISP ${id}, município do Rio de Janeiro` } }} />
    <div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#2455dc]">Região policial · CISP {id}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{area.territorialUnit}</h1><p className="mt-4 text-base leading-7 text-[#526078]">A CISP {id} reúne {area.neighborhoods.join(', ')} segundo a relação territorial do ISP-RJ. Nomes com “parte” indicam divisão do bairro entre circunscrições. Os registros representam a área policial inteira.</p><p className="mt-3 text-sm text-[#526078]">Série até {monthLabel(period)} · fonte atualizada em {sourceUpdated} · snapshot coletado em {new Date(collected).toLocaleDateString('pt-BR', { timeZone: 'UTC' })}.</p></div><RegionMap selected={id} /></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-3" aria-label="Indicadores atuais"><div className="rounded-2xl bg-[#172235] p-5 text-white"><h2 className="text-base font-semibold">Total de roubos</h2><strong className="mt-3 block text-4xl tabular-nums">{fmt(current?.count)}</strong><p className="mt-2 text-sm text-white/80">casos · {windowLabel(period, 12)}</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-base font-semibold">Taxa de roubos</h2><strong className="mt-3 block text-4xl tabular-nums">{fmt(current?.rate, 1)}</strong><p className="mt-2 text-sm text-[#526078]">casos por 100 mil moradores</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-base font-semibold">População residente</h2><strong className="mt-3 block text-4xl tabular-nums">{fmt(pop?.population)}</strong><p className="mt-2 text-sm text-[#526078]">Censo 2022 · {fmt(pop?.sectors)} setores</p></div></section>
    <section className="mt-6 rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Comparação equivalente</h2><p className="mt-2 leading-7">{current?.previous == null ? 'Janela anterior indisponível.' : <>Nos 12 meses anteriores: <strong>{fmt(current.previous)} casos</strong>. Janela atual: <strong>{fmt(current.count)} casos</strong>. {current.change == null ? 'Variação percentual omitida porque o volume anterior é inferior a 20 casos ou zero.' : <>Variação: <strong>{fmt(current.change, 1)}%</strong>.</>}</>}</p><p className="mt-2 text-sm text-[#526078]">Ambas as janelas têm 12 meses. A taxa usa a população residente do Censo 2022 como denominador fixo; não mede risco individual.</p></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Outros indicadores na CISP {id}</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{others.map(({ meta, value }) => <a className="rounded-2xl border border-[#dce2ed] bg-white p-5 transition hover:border-[#2455dc]" href={`/indicadores/${meta.id}`} key={meta.id}><h3 className="font-semibold text-[#2455dc]">{meta.label}</h3><strong className="mt-3 block text-3xl tabular-nums">{fmt(value?.count)}</strong><span className="text-sm text-[#526078]">{meta.unit} · últimos 12 meses</span></a>)}</div><p className="mt-3 text-sm text-[#526078]">Categorias podem se sobrepor. Casos, vítimas e registros de ocorrência têm unidades distintas e não são somados.</p></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><SeriesTable rows={monthlySeries(primary.id, id)} unit={primary.unit} /><div className="space-y-5"><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Bairros relacionados</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{area.neighborhoods.map((name) => <li key={name}>{name}</li>)}</ul><p className="mt-3 text-sm text-[#526078]">Relação oficial do ISP-RJ; não é uma repartição das ocorrências entre bairros.</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Continue a exploração</h2><div className="mt-3 flex flex-col gap-3 text-sm font-semibold text-[#2455dc]"><a className="underline" href={`/${queryFor(id)}`}>Abrir no mapa</a><a className="underline" href={`/meu-bairro${queryFor(id)}`}>Explorar esta região</a><a className="underline" href={`/comparar${queryFor(id)}`}>Comparar</a><a className="underline" href={`/historico?indicador=total_roubos&cisp=${id}`}>Ver histórico</a><a className="underline" href="/dados">Baixar os dados</a></div></div></div></section>
    <div className="mt-7"><SourceNote /></div>
  </PageShell>;
}
