/* oxlint-disable next/no-html-link-for-pages */
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { BreadcrumbLd, JsonLd, PageShell, RegionMap, SeriesTable, SourceNote } from '@/components/organic-ui';
import { cityMetric, rankMetrics } from '@/lib/crime-analysis';
import { ORIGIN, areaById, canonical, collected, fmt, ids, indicatorList, metrics, monthLabel, monthlySeries, period, populationById, queryFor, sourceUpdated, windowLabel } from '@/lib/organic-data';
import { pilotForRelatedName } from '@/lib/neighborhood-pages';
import { TerritoryAction, TerritoryEyebrow } from '@/components/territory-ui';

type Params = { params: Promise<{ slug: string }> };
function idFor(slug: string) { const match = /^cisp-([1-9]\d*)$/.exec(slug); return match ? Number(match[1]) : null; }
export function generateStaticParams() { return ids.map((id) => ({ slug: `cisp-${id}` })); }
export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const id = idFor((await params).slug) ?? 0, area = areaById(id);
  if (!area) return { title: 'CISP inexistente' };
  return { title: `CISP ${id} · ${area.territorialUnit} | Mapa da Criminalidade RJ`, description: `Taxas por 100 mil moradores, posições entre as 41 CISPs, registros policiais e série mensal da CISP ${id}, ${area.territorialUnit}. Dados até ${monthLabel(period)}.`, alternates: { canonical: canonical(`/regioes/cisp-${id}`) }, openGraph: { title: `CISP ${id} · ${area.territorialUnit}`, url: canonical(`/regioes/cisp-${id}`) } };
}
function rankingHref(indicator: string, view: 'taxa' | 'quantidade') {
  return `/rankings?${new URLSearchParams({ indicador: indicator, meses: '12', fim: period, comparacao: 'year', visualizacao: view })}`;
}
export default async function Region({ params }: Params) {
  const id = idFor((await params).slug) ?? 0, area = areaById(id);
  if (!area) notFound();
  const pop = populationById(id);
  const indicators = indicatorList.map((meta) => {
    const rows = metrics(meta.id);
    return { meta, value: rows.find((row) => row.cisp === id), rateRank: rankMetrics(rows, 'rate').find((row) => row.cisp === id), countRank: rankMetrics(rows, 'count').find((row) => row.cisp === id), cityRate: cityMetric(rows).rate };
  });
  const primary = indicators.find((item) => item.meta.id === 'total_roubos')!;
  const current = primary.value;
  const others = ['total_furtos', 'roubo_rua', 'letalidade_violenta'].map((key) => indicators.find((item) => item.meta.id === key)!);
  const path = `/regioes/cisp-${id}`;
  const periodText = windowLabel(period, 12);
  const relatedPilots = area.neighborhoods.flatMap((name) => { const item = pilotForRelatedName(name); return item ? [item] : []; }).filter((item, index, all) => all.findIndex((candidate) => candidate.slug === item.slug) === index);
  return <PageShell crumbs={[{ label: 'Regiões', path: '/regioes' }, { label: `CISP ${id}` }]}>
    <BreadcrumbLd items={[{ name: 'Regiões', path: '/regioes' }, { name: `CISP ${id}`, path }]} />
    <JsonLd value={{ '@context': 'https://schema.org', '@type': 'WebPage', '@id': `${ORIGIN}${path}#webpage`, url: `${ORIGIN}${path}`, name: `CISP ${id} · ${area.territorialUnit}`, description: `Taxas, posições e registros policiais da CISP ${id} até ${monthLabel(period)}.`, isPartOf: { '@id': `${ORIGIN}/#website` }, spatialCoverage: { '@type': 'Place', name: `CISP ${id}, município do Rio de Janeiro` } }} />
    <div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div><TerritoryEyebrow>Região policial · CISP {id}</TerritoryEyebrow><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{area.territorialUnit}</h1><p className="mt-4 text-base leading-7 text-[#526078]">A CISP {id} reúne {area.neighborhoods.join(', ')} segundo a relação territorial do ISP-RJ. Nomes com “parte” indicam divisão do bairro entre circunscrições. Os registros representam a área policial inteira.</p>{relatedPilots.length > 0 && <div className="mt-5"><p className="text-sm font-semibold">Perfis de bairro relacionados</p><div className="mt-2 flex flex-wrap gap-2">{relatedPilots.map((pilot) => pilot && <TerritoryAction key={pilot.slug} href={`/bairros/${pilot.slug}`}>{pilot.name}: Censo e transporte</TerritoryAction>)}</div></div>}<p className="mt-3 text-sm text-[#526078]">Série até {monthLabel(period)} · fonte atualizada em {sourceUpdated} · snapshot coletado em {new Date(collected).toLocaleDateString('pt-BR', { timeZone: 'UTC' })}.</p></div><RegionMap selected={id} /></div>
    <section className="mt-8" aria-label="Resumo de roubos"><h2 className="text-2xl font-semibold">Roubos na CISP {id}</h2><p className="mt-2 text-sm text-[#526078]">{periodText} · mesma janela de 12 meses para todas as 41 CISPs do município.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-[#172235] p-5 text-white"><h3 className="text-base font-semibold">Total de roubos</h3><strong className="mt-3 block text-4xl tabular-nums">{fmt(current?.count)}</strong><p className="mt-2 text-sm text-white/80">casos registrados</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h3 className="text-base font-semibold">Taxa de roubos</h3><strong className="mt-3 block text-4xl tabular-nums">{fmt(current?.rate, 1)}</strong><p className="mt-2 text-sm text-[#526078]">casos por 100 mil moradores</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h3 className="text-base font-semibold">Posição por taxa</h3><strong className="mt-3 block text-4xl tabular-nums">{primary.rateRank ? `${primary.rateRank.rank}ª` : '—'}</strong><p className="mt-2 text-sm text-[#526078]">maior taxa entre 41 CISPs{primary.rateRank?.tied ? ' · empate' : ''} · <a className="text-[#2455dc] underline" href={rankingHref(primary.meta.id, 'taxa')}>ver ranking</a></p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h3 className="text-base font-semibold">Posição por quantidade</h3><strong className="mt-3 block text-4xl tabular-nums">{primary.countRank ? `${primary.countRank.rank}ª` : '—'}</strong><p className="mt-2 text-sm text-[#526078]">maior número entre 41 CISPs{primary.countRank?.tied ? ' · empate' : ''} · <a className="text-[#2455dc] underline" href={rankingHref(primary.meta.id, 'quantidade')}>ver ranking</a></p></div></div><p className="mt-3 text-sm text-[#526078]">As posições ordenam registros do maior para o menor valor. Não classificam segurança nem risco individual.</p></section>
    <section className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Comparação com o município</h2><p className="mt-2 text-base leading-7">Taxa da CISP: <strong>{fmt(current?.rate, 1)}</strong> · taxa do município: <strong>{fmt(primary.cityRate, 1)}</strong> casos por 100 mil moradores no mesmo período.</p><p className="mt-2 text-sm text-[#526078]">A taxa municipal usa a soma dos registros e da população das 41 CISPs.</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">População usada na taxa</h2><strong className="mt-2 block text-2xl tabular-nums">{fmt(pop?.population)} moradores</strong><p className="mt-2 text-sm text-[#526078]">Censo 2022 · {fmt(pop?.sectors)} setores. Denominador fixo: taxa = registros nos 12 meses ÷ moradores × 100 mil.</p></div></section>
    <section className="mt-6 rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Comparação equivalente</h2><p className="mt-2 leading-7">{current?.previous == null ? 'Janela anterior indisponível.' : <>Nos 12 meses anteriores: <strong>{fmt(current.previous)} casos</strong>. Janela atual: <strong>{fmt(current.count)} casos</strong>. {current.change == null ? 'Variação percentual omitida porque o volume anterior é inferior a 20 casos ou zero.' : <>Variação: <strong>{fmt(current.change, 1)}%</strong>.</>}</>}</p><p className="mt-2 text-sm text-[#526078]">Ambas as janelas têm 12 meses. A taxa usa a população residente do Censo 2022 como denominador fixo; não mede risco individual.</p></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Outros indicadores na CISP {id}</h2><p className="mt-2 text-sm text-[#526078]">{periodText} · taxa por 100 mil moradores em cada categoria.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{others.map(({ meta, value, rateRank }) => <div className="rounded-2xl border border-[#dce2ed] bg-white p-5" key={meta.id}><h3 className="font-semibold"><a className="text-[#2455dc] underline" href={`/indicadores/${meta.id}`}>{meta.label}</a></h3><strong className="mt-3 block text-3xl tabular-nums">{fmt(value?.count)}</strong><p className="text-sm text-[#526078]">{meta.unit} · 12 meses</p><p className="mt-3 text-sm">Taxa: <strong>{fmt(value?.rate, 1)}</strong> por 100 mil</p><p className="mt-1 text-sm">Posição por taxa: <a className="font-semibold text-[#2455dc] underline" href={rankingHref(meta.id, 'taxa')}>{rateRank ? `${rateRank.rank}ª de 41` : 'Indisponível'}</a>{rateRank?.tied ? ' · empate' : ''}</p></div>)}</div><p className="mt-3 text-sm text-[#526078]">Categorias podem se sobrepor. Casos, vítimas e registros de ocorrência têm unidades distintas e não são somados.</p></section>
    <section className="mt-8"><h2 className="text-2xl font-semibold">Todos os indicadores da CISP {id}</h2><p className="mt-2 text-sm text-[#526078]">{periodText} · posição pela taxa entre as 41 CISPs, do maior para o menor valor. Empates compartilham a mesma posição.</p><div className="mt-4 overflow-x-auto rounded-2xl border border-[#dce2ed] bg-white"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-[#eaf0fc]"><tr><th className="px-4 py-3">Indicador</th><th className="px-4 py-3 text-right">Quantidade</th><th className="px-4 py-3 text-right">Taxa por 100 mil</th><th className="px-4 py-3 text-right">Posição por taxa</th></tr></thead><tbody>{indicators.map(({ meta, value, rateRank }) => <tr className="border-t border-[#e7ebf2]" data-indicator={meta.id} key={meta.id}><th className="px-4 py-3 font-medium" scope="row"><a className="text-[#2455dc] underline" href={`/indicadores/${meta.id}`}>{meta.label}</a><span className="block text-xs text-[#526078]">{meta.unit}</span></th><td className="px-4 py-3 text-right tabular-nums">{fmt(value?.count)}</td><td className="px-4 py-3 text-right tabular-nums">{fmt(value?.rate, 1)}</td><td className="px-4 py-3 text-right tabular-nums"><a className="text-[#2455dc] underline" href={rankingHref(meta.id, 'taxa')}>{rateRank ? `${rateRank.rank}ª de 41${rateRank.tied ? ' (empate)' : ''}` : 'Indisponível'}</a></td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-[#526078]">Uma taxa divide registros, casos ou vítimas pela população residente. Ela não ajusta circulação de pessoas, subnotificação ou local do fato, que pode diferir do local do registro.</p></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><SeriesTable rows={monthlySeries(primary.meta.id, id)} unit={primary.meta.unit} /><div className="space-y-5"><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Bairros relacionados</h2><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{area.neighborhoods.map((name) => <li key={name}>{name}</li>)}</ul><p className="mt-3 text-sm text-[#526078]">Relação oficial do ISP-RJ; não é uma repartição das ocorrências entre bairros.</p></div><div className="rounded-2xl border border-[#dce2ed] bg-white p-5"><h2 className="text-lg font-semibold">Continue a exploração</h2><div className="mt-3 flex flex-col gap-3 text-sm font-semibold text-[#2455dc]"><a className="underline" href={`/${queryFor(id)}`}>Abrir no mapa</a><a className="underline" href={`/meu-bairro${queryFor(id)}`}>Explorar esta região</a><a className="underline" href={`/comparar${queryFor(id)}`}>Comparar</a><a className="underline" href={`/historico?indicador=total_roubos&cisp=${id}`}>Ver histórico</a><a className="underline" href="/dados">Baixar os dados</a></div></div></div></section>
    <div className="mt-7"><SourceNote /></div>
  </PageShell>;
}
